### ISSUE TITLE
Issues with example

### ISSUE THREAD

**Issue by shibdib** [psecio/oauth2-discord#2]
`Fatal error: Class 'League\OAuth2\Client\Provider\AbstractProvider' not found in /var/www/firetail/vendor/psecio/oauth2-discord/src/Provider/Discord.php on line 12`

is what I get

**Comment by enygma** [comment]
This package is an extension for use with the [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client) and assumes you have that installed prior to use. I guess I could make that a dependency so this wouldn't pop up again...

**Comment by shibdib** [comment]
that sorted that issue.. getting unknown error after I sign in to discord now

https://discordapp.com/oauth2/authorize?state=d2401e29dcbc2bf95fae70cabb7e9247&scope=guilds.join%20bot&response_type=code&approval_prompt=auto&redirect_uri=http%3A%2F%2Ffiretail.shibdib.info%2Fauth%2F&client_id=6a3d6deb2d2248a689db650c99c13431

is the url.

**Comment by shibdib** [comment]
https://i.imgur.com/NkTN4nx.png

Super helpful discord -_-

**Comment by shibdib** [comment]
New error

`Fatal error: Uncaught TypeError: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResponse() must be of the type array, string given`

issue is with the following portion

`$accessToken = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
]);`

tried removing 'authorization_code' as it's a string and I'm out of ideas and it just throws a different error.
